name: Pipeline CI/ID
#definir quando √© rodado
on:
  push:
    branches:
      - main
  workflow_dispatch: # habilitar o bot√£o "Run workflow" no Github Actions

jobs:
  #Build
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "üêß This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "üîé The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v5
      - run: echo "üí° The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "üñ•Ô∏è The workflow is now ready to test your code on the runner."
      - name: Instal Node JS
        uses: actions/setup-node@v5
        with:
          node-version: "25"
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: Instala√ß√£o das dep√™ndencias
        run: npm install
      - name: Rodar build
        run: npm run build
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "üçè This job's status is ${{ job.status }}."
  lints:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Instal Node JS
        uses: actions/setup-node@v5
        with:
          node-version: "25"
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: Instala√ß√£o das dep√™ndencias
        run: npm install
      - name: Rodar lint
        run: npm run lint
      - name: Verificar formta√ß√£o
        run: npm run format:check
  tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Instal Node JS
        uses: actions/setup-node@v5
        with:
          node-version: "25"
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: Instala√ß√£o das dep√™ndencias
        run: npm install
      - name: Rodar testes
        run: npm run test
  deploy:
    runs-on: ubuntu-latest
    needs: [build, lints, tests]
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Instal Node JS
        uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Deploy to Vercel
        run: |
          npx vercel pull --yes --environment=production --token=${{ env.VERCEL_TOKEN }}
          npx vercel build --prod --token=${{ env.VERCEL_TOKEN }}
          npx vercel deploy --prebuilt --prod --token=${{ env.VERCEL_TOKEN }}
